import { makeStyles } from "@material-ui/core";
export default makeStyles((theme) => ({
  roundSales: {
    width: "100%",
    height: "auto",
    paddingTop: "50px",
    paddingBottom: "100px",
    backgroundColor: theme.palette.secondary.main,
  },
  mainBox: {
    width: "100%",
    height: 600,
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    [theme.breakpoints.down("md")]: {
      height: "auto",
      flexDirection: "column",
    },
  },
  boxLeft: {
    width: 395,
    height: 470,
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: (dark) => (dark ? "rgb(22, 23, 26)" : "#fafafa"),
    position: "relative",
    [theme.breakpoints.down("md")]: {
      margin: "100px 0",
    },
    [theme.breakpoints.down("xs")]: {
      width: "100%",
    },
    "&::before": {
      content: '"pre-sale"',
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textTransform: "uppercase",
      color: "white",
      fontSize: 18,
      width: 175,
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      height: 40,
      marginTop: -40,
      fontWeight: "bold",
      background: "linear-gradient(to right, #fdc830, #f37335)",
    },
  },
  boxRight: {
    width: 395,
    height: 470,
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: (dark) => (dark ? "rgb(22, 23, 26)" : "#fafafa"),
    position: "relative",
    [theme.breakpoints.down("xs")]: {
      width: "100%",
    },
    "&::before": {
      content: '"ico"',
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      color: "white",
      textTransform: "uppercase",
      fontSize: 18,
      width: 175,
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      height: 40,
      marginTop: -40,
      fontWeight: "bold",
      background: "linear-gradient(to right, #fdc830, #f37335)",
    },
  },
  boxTitle: {
    fontSize: 18,
    marginTop: 50,
    marginBottom: 25,
  },
  btnTxt: {
    width: 270,
    height: 60,
    borderRadius: 50,
    cursor: "pointer",
    border: "2px solid #e3e4e6",
    textTransform: "none",
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 50,
  },
  proBox: {
    border: "2px solid gray",
    borderRadius: 100,
    width: 150,
    height: 150,
    marginTop: 30,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  btnTxtCont: {
    width: 270,
    height: 60,
    borderRadius: 50,
    cursor: "pointer",
    textTransform: "none",
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 50,
    color: "white",
    background: "linear-gradient(to right, #fdc830, #f37335)",
    transition: "all 0.3s ease-in",
    "&:hover": {
      background: "linear-gradient(to left, #fdc830, #f37335)",
    },
  },
  icoBox: {
    width: "60%",
    height: 200,
    display: "flex",
  },
  timeBox: {
    width: "60%",
    height: 200,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "start",
  },
  bonusBox: {
    width: "40%",
    height: 200,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
  },
  orangeSub: {
    color: "orange",
    fontSize: 20,
    fontWeight: "bold",
  },
  variantZ: {
    color: (dark) => (dark ? "rgba(255, 255, 255, 0.61)" : "#222"),
    fontSize: 20,
  },
}));
